config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "dogs#new"

  resources :dogs, only: [:create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dog.rb
# frozen_string_literal: true

class Dog < ApplicationRecord
  has_many :images, dependent: :destroy
  validates :breed, presence: true
  validates :breed, uniqueness: true
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :dog
  validates :url, presence: true
  validates :url, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
# frozen_string_literal: true

class DogsController < ApplicationController
  before_action :set_breed, only: :create

  def create
    status, response, code = Api::V1::Dog::BreedImage.call(@breed)
    render :new, status: :ok,
                 locals: { response: response, breed: @breed, status: status, code: code }
  end

  private

  def set_breed
    @breed = params[:dog][:breed]

    render json: { error: "Dog breed is missing" }, status: :not_found unless @breed
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/new.html.haml
%section.padding-10
  .lg:flex.lg:items-center.lg:justify-between
    .min-w-0.flex-4
      %h2.text-2xl.font-bold.leading-7.text-gray-900.sm:truncate.sm:text-3xl.sm:tracking-tight
        = t('animal.new.title')
  = turbo_frame_tag 'anyframe' do
    %div
      = form_with scope: :dog, url: dogs_path, local: true do |form|
        = form.label :breed, t('animal.new.form.label.breed'), class: 'block text-sm font-medium leading-6 text-gray-900'
        = form.text_field :breed, required: true, value: "#{local_assigns[:breed] || nil}", class: 'lock w-full rounded-md border-0 py-1.5 pl-7 pr-20 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 width-400 input-field'
        = form.submit t('button.submit'), class: 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800'
      %div
        - if local_assigns[:breed]
          %div
            %h2
              Result of #{local_assigns[:breed]}
            - if local_assigns[:status] == 'error'
              %p.error= local_assigns[:response]
            - else
              %p= image_tag(local_assigns[:response])

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>